# Generated by Django 4.0 on 2022-06-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_shift_end_time_shift_length_shift_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='date',
            field=models.CharField(default='not today', max_length=100),
            preserve_default=False,
        ),
    ]
