# Generated by Django 4.0 on 2022-06-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_shift_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Select', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='location',
            field=models.CharField(choices=[('O1', 'O1'), ('O2', 'O2'), ('O3', 'O3')], max_length=20),
        ),
    ]
