# Generated by Django 4.0 on 2022-06-29 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_shift_day_alter_shift_date_alter_shift_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='day',
            new_name='weekday',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='date',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='length',
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('date', models.DateField(null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(choices=[('O1', 'O1'), ('O2', 'O2'), ('O3', 'O3')], max_length=20)),
                ('length', models.DurationField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.user')),
            ],
        ),
    ]
